repos:
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright --pythonversion 3.13
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
